dataset:
  train_file: ../my_datasets/learning-agency-lab-automated-essay-scoring-2/train.csv
  fold_file: ../my_datasets/folds/folds4.csv
  external: null
  n_samples_in_train: 12981
  remove_pc2_in_train: false
  sampling:
    enable: false
    method: by_dist
model:
  save_path: ../models/exp321_aes2-deberta-v3-large-10
  num_layers: 24
  path: /root/autodl-tmp/aes2-deberta-v3-large-10
  head: ''
  pooling: attention
  layer_start: 12
  msd: false
  num_reinit_layers: 0
  n_labels: 6
  differential_lr:
    enable: true
    lr_factor: 2.6
  llrd:
    enable: false
    value: 0.9
  task_type: regression
optim:
  optimizer:
    name: adamw8bit
    lookahead: false
    lr: 1.0e-05
    head_lr: 1.0e-05
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-06
    weight_decay: 0.01
  scheduler:
    name: linear
    warmup_percent: 0.1
    num_warmup_steps: 0
    kwargs: {}
train:
  fold: 3
  exp_name: exp321
  device: cuda
  num_folds: 4
  fullfit: false
  seed: 818
  use_random_seed: true
  ensure_data_order: false
  reinit_weights: true
  loss: mse
  new_loss_factor: 1.0
  pc2_loss_factor: 1.0
  loss_factor: -1
  accumulate_grad: 1
  max_length: 1024
  validate_max_length: 1024
  batch_size: 16
  log_steps: 25
  epochs: 2
  num_workers: 4
  max_grad_norm: 10
  validation_interval: 0.5
  precision: bf16
  gradient_checkpointing: true
  freeze_embeddings: false
  freeze_encoders: 0
  save_last_checkpoint: true
  use_wandb: true
  hyper_loss_factor: 0
  stage: 2
  use_cope: false
awp:
  tag: not implement yet
  enable: false
  from_score: 0.48
  adv_param: weight
  adv_lr: 1
  adv_eps: 0.01
  start_epoch: 1
  adv_step: 1
ema:
  tag: not implement yet
  enable: false
  from_score: 100
  decay: 0.999
mixout:
  enable: false
  p: 0.1
multi_task:
  enable: false
  weight: 0.8
  tasks:
  - readability
  path: ???
pl:
  enable: false
  path: ???
  stage: 1
  prev_model_path: ???